php72/php7.2-custom.ini, php72/php7.2-fpm.conf, php72/php7.2-upstream.conf, php72/php7.2-www.conf, php72/provision.sh
See https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1263.
I copied the files from PHP 7.1 and replaced all references to `7.1`/`71` with `7.2`/`72`.
The only difference is the lack of a `php7.2-mcrypt` module. The extension has been [deprecated in PHP 7.1](http://php.net/manual/de/migration71.deprecated.php). See also https://liorkaplan.wordpress.com/2017/09/10/php-7-2-is-coming-mcrypt-extension-isnt/.
=> Add PHP 7.2

phpmyadmin/config.inc.php
This should fix the "Wrong permissions on configuration file, should not be world writable!" error when accessing phpMyAdmin on Windows machines.
=> Ignore phpmyadmin config file permission checks

php56/provision.sh, php70/provision.sh, php71/provision.sh, php72/provision.sh
fixes a PHP 7.0 typo that overwrote the 7.1 fpm config, and added mailhog support if present
=> Mailhog and PHP 7.1 fix

php72/provision.sh
On PHP 7.2 `* Copied /srv/config/php-config/mailcatcher.ini   to /etc/php/7.2/mods-available/mailcatcher.ini` is always echoed, regardless of if Mailcatcher was actually installed or not.
=> Remove Mailcatcher copied `echo` that always appears for PHP 7.2.

php56/php5.6-custom.ini, php70/php7.0-custom.ini, php71/php7.1-custom.ini, php72/php7.2-custom.ini
Since VVV 2.2.1 the logs location has been moved to /var/log instead of /srv/log.
That has since made all non-default PHP versions log to nginx default file instead if it's dedicated file.
I'm afraid this PR would break for users with VVV < 2.2.1.
Should we maybe create a pre-vvv-2.2.1 branch from the current master and then merge this PR?
That would of course also require a branch change for the utility sources here https://github.com/Varying-Vagrant-Vagrants/VVV/blob/develop/Vagrantfile#L188.
=> Update error log location to /var/log/ for all PHP versions.

memcached-admin/provision.sh
1.2.4-vvv is a php7.2 compat version of 1.3.0-upstream
when the `elijaa/phpmemcachedadmin` package tags a new release with php >=7.2 support we can switch over to the repo there.
=> first step to back to the original package. 

php56/php5.6-custom.ini, php56/php5.6-fpm.conf, php70/php7.0-custom.ini, php70/php7.0-fpm.conf, php71/php7.1-custom.ini, php71/php7.1-fpm.conf, php72/php7.2-custom.ini, php72/php7.2-fpm.conf, php73/php7.3-custom.ini, php73/php7.3-fpm.conf
They're using the `/var/log` folder, but that folder isn't shared, instead use `/var/log/php`
=> Fix PHP log locations

tideways/tideways-header.php
=> add a http header when tideways is enabled, and adjust the conditional

.gitignore, webgrind/composer.json, webgrind/provision.sh
this provisions webgrind via composer.
reduces provision time (composer).
older installs? What happens if `webgrind ` is already present?
=> WIP: provision webgrind via composer

tls-ca/provision.sh
The variable is already defined so redefine creates issues
=> Remove define of a global var

mongodb/provision.sh
Seems we never added the mongodb extension to PHP 7.4, related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2008
=> add PHP 7.4 to the list on mongodb PHP extensions to install

php/provision.sh, php56/provision.sh, php70/provision.sh, php71/provision.sh, php72/provision.sh, php73/provision.sh, php74/provision.sh
This solves `dpkg-reconfigure: unable to re-open stdin: No file or directory` appearing in the provisioner logs
=> tell dpkg to expect no interaction

tls-ca/provision.sh
related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2019 and https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2020
=> Fix shyaml site name escaping in the TLS CA

webgrind/provision.sh
This fixes composer running under the root super user during provisioning webgrind
=> fix super user root warning when provisioning webgrind

tideways/provision.sh
Looking at the code of xhgui the install.php execute `install` so doesn't involve the update of the dependencies https://github.com/perftools/xhgui/blob/master/install.php#L75
=> Update composer in xhgui during provision

mongodb/provision.sh
fix installing mongodb to new PHP versions, and switch to the more reliable apt install command
To test, adjust `config.yml` with the following and reprovision:
```yaml
utility-sources:
core:
repo: https://github.com/Varying-Vagrant-Vagrants/vvv-utilities.git
branch: tomjn/mongodb-php-fix
```
=> MongoDB PHP fixes

mongodb/provision.sh
This fixes error: `Unable to locate package mongodb-org,`
=> MongoDB - Fix incorrect package name

tls-ca/openssl-default-cert.conf, tls-ca/openssl-site-stub.conf, tls-ca/provision.sh
refactored the TLS CA to use bash functions for everything, set the certificate expiry days as variables, and moved the openssl config stuff to files
Recreates some of what was in #56, this should work the same as before, but structured better
=> TLS-CA bash functions

tls-ca/provision.sh
Double quote to prevent globbing and word splitting.
=> TLS CA codacy globbing fixes

tideways/provision.sh
Moves compiling for PHP around a bit
As an aside, we need to set the default PHP back to the default at the end, otherwise when it builds tideways it'll end up on the most recently installed version of PHP
Perhaps VVV core can set the default in the post provision trigger too
=> minor refactors to the tideways provisioner

tideways/provision.sh
Otherwise
```
default: cp: 
default: cannot stat '/srv/provision/utilities/core/mongodb/tideways-header.php'
default: : No such file or directory
default: cp: 
default: cannot stat '/srv/provision/utilities/core/mongodb/tideways.ini'
default: : No such file or directory
default: cp: 
default: cannot stat '/srv/provision/utilities/core/mongodb/xhgui-php.ini'
default: : No such file or directory
default: cp: 
default: cannot stat '/srv/provision/utilities/core/mongodb/tideways.ini'
default: : No such file or directory
default: cp: 
default: cannot stat '/srv/provision/utilities/core/mongodb/xhgui-php.ini'
default: : No such file or directory
default: cp: 
default: cannot stat '/srv/provision/utilities/core/mongodb/nginx.conf'
```
=> Fix tideways provision after #61

php80/provision.sh
This PR removes `php8.0-json` from the list of packages installed by php80/provision.sh. In PHP 8.0, `ext-json` is always available. I'm guessing that is why there is no `php8.0-json` package. The first time that I tried to provision php80 in my vvv install I got the following error:
```
$ vagrant provision --provision-with utility-core-php80
(...)
==> default: Running provisioner: utility-core-php80 (shell)...
default: Running: /tmp/vagrant-shell20201016-18935-5ekxp.sh
default:  ▷ Running the 'utility-core-php80' provisioner...
default: E: Package 'php8.0-json' has no installation candidate
default: cp: cannot create regular file '/etc/php/8.0/fpm/php-fpm.conf': No such file or directory
default: cp: cannot create regular file '/etc/php/8.0/fpm/pool.d/www.conf': No such file or directory …
```
=> Remove php8.0-json from php80/provision.sh

opcache-gui/provision.sh
In this way in the log we don't have this output, it is forcing the creation every time and keep constistency with other utilities:
```
default: ln: 
default: failed to create symbolic link './index.php'
default: : File exists
```
=> Force creation of symlink

tideways/provision.sh
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2288
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2290
https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2261
=> Mte90 /fix xhgui tickets

tideways/provision.sh
If something goes wrong we need to see what went wrong. Piping to /dev/null gives no benefits and makes our lives much harder. We already redirect output to a logfile so that it doesn't fill the terminal.
Also switched the composer/git commands to avoid rebasing, and installed sqlite3 for PHP v8.0
=> Replace rebase and remove /dev/null pipes in XHGUI/Tideways Provisioner

tideways/provision.sh, tls-ca/provision.sh
Handle support for https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2328 by improving vvv config detection
=> config change support

tideways/tideways-header.php
Allow tideways to run if ENABLE_TIDEWAYS_CLI is defined as an environment variable
In theory something like this would work:
```sh
export ENABLE_TIDEWAYS_CLI=1
wp ...
```
=> Tideways CLI

tideways/config.php-profiler.php
The php-profiler explains that also this autoload is required
=> Fix for missing methods

tideways/config.php-profiler.php
As we don't install tideways for CLI
Otherwise we get:
```
default:  ▷ Running the 'site-community' provisioner...
default:  * Pulling down the master branch of https://github.com/Varying-Vagrant-Vagrants/custom-site-template
default: From https://github.com/Varying-Vagrant-Vagrants/custom-site-template
default:  * branch            master     -> FETCH_HEAD
default: Failed to load the PHP Profiler autoloader.php file, confirm provisioning of tideways was succesful, reprovision, and if all else fails delete the php-profiler folder in /srv/www/default and report on the VVV github
default: Failed to load the PHP Profiler autoloader.php file, confirm provisioning of tideways was succesful, reprovision, and if all else fails delete the php-profiler folder in /srv/www/default and report on the …
```
=> Don't load php-profiler on CLI

php/provision.sh, php82/fpm.conf, php82/php-custom.ini, php82/provision.sh, php82/upstream.conf, php82/www.conf
This PR adds PHP 8.2 as an option since packages for this PHP version are already available in Ondrej's PPA. It is basically a copy of #94, but for PHP 8.2 instead of 8.1.
The only gotcha is that some of the PHP modules that are typically installed are still not available for PHP 8.2 and I'm not sure what is the best way to handle that (see commit 72efd09eff9ee003c7566910fb6fdc9a418bde07 for the list of packages). Regardless of the missing modules, being able to run PHP 8.2 inside VVV was useful for me to prepare for the next PHP release, so I'm sharing this PR here in case it is useful for others.
=> Add PHP 8.2

php82/provision.sh, php83/provision.sh
These packages weren't ready at first but they should be now
=> Enable commented out packages in newer PHP versions
