- php56/php5.6-custom.ini
- php56/php5.6-fpm.conf
- php56/php5.6-upstream.conf
- php56/php5.6-www.conf
- php56/provision.sh
- php71/php7.1-custom.ini
- php71/php7.1-fpm.conf
- php71/php7.1-upstream.conf
- php71/php7.1-www.conf
- php71/provision.sh
This makes Varying-Vagrant-Vagrants/vvv#1055 useful.
> Add PHP5.6 && PHP7.1

- phpmyadmin/provision.sh
Changes: https://www.phpmyadmin.net/news/2017/3/29/phpmyadmin-470-released/
> phpMyAdmin: Update to 4.7.0

- webgrind/provision.sh
the original author has picked up the project again.
we are a few releases behind with the fork we have been using.
> load webgrind from the original repo (is up and running again)

- tls-ca/provision.sh
A certificate authority generating cartificates for every domain in vvv-config.yml automagically 💃
_This took way longer than i wanted to spend on it._
> [Beta] CA: Initial Commit

- phpmyadmin/provision.sh
Closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1535#issuecomment-393527645
> Update PHPMyAdmin to 4.8.1

- php73/php7.3-custom.ini
- php73/php7.3-fpm.conf
- php73/php7.3-upstream.conf
- php73/php7.3-www.conf
- php73/provision.sh
closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1651
> adds a PHP 7.3 utility, untested

- phpmyadmin/provision.sh
Changes: https://www.phpmyadmin.net/news/
> Update phpMyAdmin to 4.8.5

- mongodb/provision.sh
This should fix the issue for https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1815
> set path for chown in mongodb

- memcached-admin/provision.sh
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1822
> Copy config file for memcached-admin

- tls-ca/provision.sh
closes https://github.com/Varying-Vagrant-Vagrants/VVV/issues/1820
> improve logging, and add the root certificate to the VM

- php56/provision.sh
- php70/provision.sh
- php71/provision.sh
- php72/provision.sh
- php73/provision.sh
- php74/provision.sh
This fixes WP CLI notices etc gumming up provisioning the contributor environment
> switch to 7.2 on CLI after PHP 7.4 is installed

- tideways/tideways-header.php
don't run tideways on CLI, and simplify the conditionals for loading tideways
> Adjust Tideways loading

- tls-ca/provision.sh
Improves Catalina compatibility
> change expiration from 10 years to 200 days

- tls-ca/provision.sh
add extendedKeyUsage section, extra distinguished attributes, and fixed an escaping bug with dots
> TLS CA improvements

- php56/provision.sh
- php70/provision.sh
- php71/provision.sh
- php72/provision.sh
- php73/provision.sh
- php74/provision.sh
Support PHP pcov to improve coverage checking speed for PHPUnit 8+
> added php-pcov to the install list for PHP versions

- php56/php5.6-fpm.conf
- php70/php7.0-fpm.conf
- php71/php7.1-fpm.conf
- php72/php7.2-fpm.conf
- php73/php7.3-fpm.conf
- php74/php7.4-fpm.conf
> fix the FPM PID values

- tls-ca/provision.sh
Possibly related to https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2155
> Always copy and update installed certificates

- php56/provision.sh
- php70/provision.sh
- php71/provision.sh
- php72/provision.sh
- php73/provision.sh
- php74/provision.sh
Partial fix for https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2178. See also https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2179.
> install intl module for PHP

- nvm/README.md
- nvm/provision.sh
Added `nvm` provisioner as an optional core utility for VVV
Ref: https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2177
> Added NVM as a core utility

- svn-folder-upgrade/provision.sh
The core provisioner does this, but it's only really applicable to a very small number of people, so lets put it in a utility and remove it from a future version so it isn't mandatory
> Add an svn folder upgrade utility

- opcache-gui/README.md
- opcache-gui/provision.sh
- opcache-status/provision.sh
Fix https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2149
> Opcache GUI utility with alert on opcache-status

- phpmyadmin/config.inc.php
- phpmyadmin/provision.sh
Update to 4.9.7, and improve the provisioner slightly
> update phpMyAdmin to v4.9.7

- README.md
- php56/provision.sh
- php70/provision.sh
- php71/provision.sh
- php72/provision.sh
- php73/provision.sh
- php74/provision.sh
- php80/provision.sh
Similar to https://github.com/Varying-Vagrant-Vagrants/VVV/pull/2310
> use PHP specific versions of packages

- README.md
- php56/provision.sh
- php70/provision.sh
- php71/provision.sh
- php72/provision.sh
- php73/provision.sh
- php74/provision.sh
- php80/provision.sh
Reverts Varying-Vagrant-Vagrants/vvv-utilities#79
> Revert "use PHP specific versions of packages"

- nvm/provision.sh
> Update nvm version

- php56/provision.sh
- php70/provision.sh
- php71/provision.sh
- php72/provision.sh
- php73/provision.sh
- php74/provision.sh
- php80/provision.sh
This may help with xdebug changes and robustness, but it needs testing
> add new PHP specific versions of packages

- tideways/config.php-profiler.php
- tideways/provision.sh
Fix: 
* https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2251
* https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2365
* Add php 8.0
> Tideways improvements

- yarn/provision.sh
Adds a yarn utility, undecided if this should just be in VVV core or a part of a general npm global package list feature in `config.yml`
> add yarn utility

- tideways/nginx.conf
- tideways/provision.sh
ensure 7.3 is installed and make XHGui use it until they've migrated upstream
> XHGui PHP 7.3

- tideways/provision.sh
I tested it and everything seems working with php 7.4
> Bump php min version and xhgui

- mongodb/provision.sh
> Update php version for mongodb

- tideways/config.php-profiler.php
Removed try/catch exposed a syntax error.
> Fix syntax error

- opcache-status/provision.sh
- tideways/config.php-profiler.php
- tideways/provision.sh
make the paths explicit rather than relative for some xhgui installation steps
> XHGui setup adjustments

- memcached-admin/provision.sh
- mongodb/provision.sh
- opcache-gui/provision.sh
- opcache-status/provision.sh
- phpmyadmin/provision.sh
- tideways/provision.sh
- tls-ca/provision.sh
- webgrind/provision.sh
- Bump phpmyadmin version
- misc shellcheck fixes
- add 8.2 to several places it was missing
> Misc shellcheck fixes

- elasticsearch/provision.sh
- elasticsearch/readme.md
> Elastic search provisioner

- tideways/config.php
* Add missing tideways PDO configuration parameter
See [vvv-utilities/#108](https://github.com/Varying-Vagrant-Vagrants/VVV/issues/2697) for details.
> Add tideways missing PDO param

- mongodb/provision.sh
- tideways/provision.sh
Adds 8.3 to the list in tideways provisioner
> Support PHP 8.3 in Tideways

- php83/upstream.conf
Bug spotted at https://github.com/Varying-Vagrant-Vagrants/vvv-utilities/pull/107#pullrequestreview-1832079431
> Fix php8.3

- webgrind/composer.json
Fixes this extension from failing
> Allow webgrind composer installer plugins

- .gitignore
- php/provision.sh
- php84/fpm.conf
- php84/php-custom.ini
- php84/provision.sh
- php84/upstream.conf
- php84/www.conf
- tideways/provision.sh
> PHP 8.4 extension
